<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>IPA Transfer {{ $transfer->transfer_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111; }
        h1 { font-size: 18px; margin-bottom: 4px; }
        .meta { margin-bottom: 16px; }
        .meta td { padding: 2px 12px 2px 0; vertical-align: top; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 12px; }
        table.items th, table.items td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
        table.items th { background: #f5f5f5; }
        .footer { margin-top: 24px; font-size: 10px; color: #666; }
    </style>
</head>
<body>
    <h1>Internal Plant Assignment (IPA) Transfer</h1>
    <p><strong>{{ $transfer->transfer_number }}</strong></p>

    <table class="meta">
        <tr>
            <td><strong>Transferred at</strong></td>
            <td>{{ $transfer->transferred_at->format('d M Y H:i') }}</td>
            <td><strong>By</strong></td>
            <td>{{ $transfer->user->name }}</td>
        </tr>
        <tr>
            <td><strong>From project</strong></td>
            <td>{{ $transfer->from_project_code ?? '—' }}</td>
            <td><strong>To project</strong></td>
            <td>{{ $transfer->to_project_code ?? '—' }}</td>
        </tr>
        <tr>
            <td><strong>From department</strong></td>
            <td>{{ $transfer->fromDepartment?->department_name ?? '—' }}</td>
            <td><strong>To department</strong></td>
            <td>{{ $transfer->toDepartment?->department_name ?? '—' }}</td>
        </tr>
    </table>

    @if($transfer->notes)
        <p><strong>Notes:</strong> {{ $transfer->notes }}</p>
    @endif

    <table class="items">
        <thead>
            <tr>
                <th>#</th>
                <th>Unit Code</th>
                <th>From Project</th>
                <th>To Project</th>
                <th>From Dept</th>
                <th>To Dept</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transfer->lines as $index => $line)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $line->unit_code ?? '—' }}</td>
                    <td>{{ $line->from_project_code ?? '—' }}</td>
                    <td>{{ $line->to_project_code ?? '—' }}</td>
                    <td>{{ $line->from_department_id ? ($line->fromDepartment?->department_name ?? '—') : '—' }}</td>
                    <td>{{ $line->to_department_id ? ($line->toDepartment?->department_name ?? '—') : '—' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <p class="footer">Generated by ArkFleet — {{ now()->format('d M Y H:i') }}</p>
</body>
</html>
